// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreeFolderStructure.DataAccess.DataAccess;

#nullable disable

namespace TreeFolderStructure.DataAccess.Migrations
{
    [DbContext(typeof(FolderContext))]
    [Migration("20220808190113_AddChildren")]
    partial class AddChildren
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TreeFolderStructure.DataAccess.Model.FolderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("FolderModelId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FolderModelId");

                    b.ToTable("Folder");
                });

            modelBuilder.Entity("TreeFolderStructure.DataAccess.Model.FolderModel", b =>
                {
                    b.HasOne("TreeFolderStructure.DataAccess.Model.FolderModel", null)
                        .WithMany("Children")
                        .HasForeignKey("FolderModelId");
                });

            modelBuilder.Entity("TreeFolderStructure.DataAccess.Model.FolderModel", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
